name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  release:
    types:
      - published
      - edited

jobs:
  ci-test:
    name: CI-Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Run npm
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Check code style
        run: npm run format
      - name: Run typecheck
        run: npm run lint:ts
      - name: Run unit test
        run: npm run test
