name: CI

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - published
      - edited

jobs:
  ci-test:
    name: CI-Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run npm
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Check code style
        run: npm run format
      - name: Run typecheck
        run: npm run lint:ts
      - name: Run jest test excluding puppeteer
        run: npm run test:no-puppeteer -- --coverage
      - name: Report test coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/**/*
          flags: unittests
      - name: Run puppeteer test
        run: npm run test:puppeteer
      - name: Run esbuild
        run: npm run build

  ci-build:
    name: CI-Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run npm
        run: npm ci
      - name: Run Docker build
        run: npm run build:docker
