name: CI

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - published
      - edited

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run npm
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Check code style
        run: npm run format
      - name: Run typecheck
        run: npm run lint:ts
      - name: Run jest test excluding puppeteer
        run: npm run test:no-puppeteer -- --coverage
      - name: Report test coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/**/*
          flags: unittests
      - name: Run puppeteer test
        run: npm run test:puppeteer
      - name: Run esbuild
        run: npm run build

  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run npm
        run: npm ci
      - name: Print info
        run: echo ${{ github.event_name }} && echo ${{ github.ref_type }} && echo ${{ github.ref_name }}
      - name: Run Docker build
        run: npm run build:docker
      - name: Check release tag version
        if: ${{ github.event_name == 'release' }}
        run: bin/check_github_release_tag.sh ${{ github.ref_name }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.event_name == 'release' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Publish image
        if: ${{ github.event_name == 'release' }}
        run: npm run publish:docker
