name: CI

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - published
      - edited

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run npm
        run: npm ci
      - name: Run Eslint
        run: npm run lint
      - name: Check code style
        run: npm run format
      - name: Run typecheck
        run: npm run lint:ts
      - name: Run tests without external dependencies
        run: npm run test:internal -- --coverage
      - name: Report test coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/**/*
          flags: unittests
      - name: Run tests with external dependencies
        run: npm run test:external
      - name: Run esbuild
        run: npm run build

  docker:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Download font
        run: bin/download_font.sh WeiRuanYaHei.ttf
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          FONT_FILE_S3_PATH: ${{ secrets.FONT_FILE_S3_PATH }}
      - name: Run npm
        run: npm ci
      - name: Run esbuild
        run: npm run build
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Check release tag version
        if: ${{ github.event_name == 'release' }}
        run: bin/check_github_release_tag.sh ${{ github.ref_name }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
